/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Action =
  | NoOpAction
  | HelpAction
  | QueryAgentRegistryAction
  | SendMessageAction
  | ListDirectory
  | ReadFile
  | WriteFile;

/**
 * Do nothing.
 */
export interface NoOpAction {
  name: "no-op";
}
/**
 * Get help on a specific action, or list all available actions.
 */
export interface HelpAction {
  name: "help";
  /**
   * The name of an action to get help on.
   */
  aboutAction?: string;
}
/**
 * Ask who the other agents are that I can talk to.
 */
export interface QueryAgentRegistryAction {
  name: "query-agent-registry";
}
/**
 * Send a message to another agent.
 */
export interface SendMessageAction {
  name: "send-message";
  /**
   * The target agent's ID.
   */
  targetAgentId: string;
  /**
   * The content of the message.
   */
  message: string;
}
/**
 * Inspect the contents of a particular directory.
 */
export interface ListDirectory {
  name: "list-directory";
  /**
   * The path of the directory you want to inspect.
   */
  path: string;
}
/**
 * Read the contents of a particular file.
 */
export interface ReadFile {
  name: "read-file";
  /**
   * The path of the file you want to inspect.
   */
  path: string;
}
/**
 * Write the contents of a particular file.
 */
export interface WriteFile {
  name: "write-file";
  /**
   * The path of the file you want to write to.
   */
  path: string;
  /**
   * The new content of the file.
   */
  newContent: string;
}
