/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Action {
  /**
   * The payload that's specific to a particular action.
   */
  payload:
    | NoOpAction
    | ViewActionDictionaryAction
    | QueryAgentRegistryAction
    | SendMessageAction
    | ListDirectory
    | ReadFile
    | WriteFile;
  /**
   * Use this field to articulate your thought process in choosing this action.
   */
  comment: string;
}
/**
 * Do nothing.
 */
export interface NoOpAction {
  type: "no-op";
}
/**
 * View the Action Dictionary which describes how to validly format your responses in JSON.
 */
export interface ViewActionDictionaryAction {
  type: "view-action-dictionary";
}
/**
 * Ask who the other agents are that I can talk to.
 */
export interface QueryAgentRegistryAction {
  type: "query-agent-registry";
}
/**
 * Send a message to another agent.
 */
export interface SendMessageAction {
  type: "send-message";
  /**
   * The target agent's ID.
   */
  targetAgentId: string;
  /**
   * The content of the message.
   */
  message: string;
}
/**
 * Inspect the contents of a particular directory.
 */
export interface ListDirectory {
  type: "list-directory";
  /**
   * The path of the directory you want to inspect.
   */
  path: string;
}
/**
 * Read the contents of a particular file.
 */
export interface ReadFile {
  type: "read-file";
  /**
   * The path of the file you want to inspect.
   */
  path: string;
}
/**
 * Write the contents of a particular file.
 */
export interface WriteFile {
  type: "write-file";
  /**
   * The path of the file you want to write to.
   */
  path: string;
  /**
   * The new content of the file.
   */
  newContent: string;
}
