/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Action = SendMessageAction;

/**
 * Send a message to another agent.
 */
export interface SendMessageAction {
  type: "send-message";
  /**
   * The target agent's ID.
   */
  agentId?: string;
  /**
   * The content of the message.
   */
  message?: string;
}
