/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Action {
  /**
   * The payload that's specific to a particular action.
   */
  payload: NoOpAction | QueryAgentRegistryAction | SendMessageAction;
  /**
   * Use this field to articulate your thought process in choosing this action.
   */
  comment: string;
}
/**
 * Do nothing.
 */
export interface NoOpAction {
  type: "no-op";
}
/**
 * Ask who the other agents are that I can talk to.
 */
export interface QueryAgentRegistryAction {
  type: "query-agent-registry";
}
/**
 * Send a message to another agent.
 */
export interface SendMessageAction {
  type: "send-message";
  /**
   * The target agent's ID.
   */
  targetAgentId: string;
  /**
   * The content of the message.
   */
  message: string;
}
