/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Event = HeartbeatEvent | MessageEvent;

/**
 * A heartbeat event that occurs periodically.
 */
export interface HeartbeatEvent {
  type: "heartbeat";
}
/**
 * A message event that is sent between agents.
 */
export interface MessageEvent {
  type: "message";
  /**
   * The sender agent's ID.
   */
  fromId: string;
  /**
   * The receiver agent's ID.
   */
  toId: string;
  /**
   * The content of the message.
   */
  message: string;
}
