/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Event {
  /**
   * The ID of the agent for whom this event is intended. If empty, no agents will receive it. If null, all agents will receive it.
   */
  targetAgentIds?: string[];
  payload: HeartbeatEvent | MessageEvent | ErrorEvent;
}
/**
 * A heartbeat event that occurs periodically.
 */
export interface HeartbeatEvent {
  type: "heartbeat";
}
/**
 * A message event that is sent between agents.
 */
export interface MessageEvent {
  type: "message";
  /**
   * The sending agent's ID.
   */
  sourceAgentId?: string;
  /**
   * The content of the message.
   */
  message: string;
}
/**
 * An indication that something went wrong.
 */
export interface ErrorEvent {
  type: "error";
  /**
   * Information about the error.
   */
  message: string;
}
